name: "Hello world!"
on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Say hello
        run: echo "Hello world!"
      - name: Show current date
        run: date
      - name: List files
        run: ls -l
